RANDOM_SEED = 42

TASK_TYPE__SEQUENCE_TAGGING = 0
TASK_TYPE__SENTENCE_CLASSIFICATION = 1
TASK_TYPE__TWO_SENTENCES_CLASSIFICATION = 2

GENERATOR__TRAIN = 0
GENERATOR__TEST = 1
GENERATOR__VALIDATION = 2

CORPUS__SENTENCE_SEPERATOR = "&&&"